=== Janko-dev/jabberpoint/resources/jabberpoint.dtd
<!--
 Document Type Definition voor JabberPoint presentatties
 $Id$
 -->
        <!ELEMENT slideshow (title, author, date, slide+)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT slide (text|image|list|table)*>
        <!ELEMENT text (#PCDATA)>
        <!ELEMENT image EMPTY>
        <!ATTLIST image src CDATA #REQUIRED>
        <!ELEMENT list (text|image|list|table)*>
        <!ELEMENT table (list)*>
        <!ATTLIST table rows CDATA #REQUIRED>
        <!ATTLIST table cols CDATA #REQUIRED>

<!--        <!ELEMENT item (#PCDATA)>-->
<!--        <!ATTLIST item kind CDATA #REQUIRED>-->
<!--        <!ATTLIST item level CDATA #REQUIRED>-->

=== Janko-dev/jabberpoint/resources/slideshow_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE slideshow SYSTEM "jabberpoint.dtd">
<slideshow>
    <title>My first slide show</title>
    <author>John Doe</author>
    <date>02-10-2022</date>
    <slide>
        <text> test1 </text>
        <text> test2 </text>
        <text> test3 </text>
    </slide>
    <slide>
        <list>
            <text> hello world </text>
            <image src="./test_img.png"/>
            <list>
                <text> list_item1 </text>
                <text> list_item2 </text>
            </list>
        </list>
    </slide>
    <slide>
        <table rows="2" cols="2">
            <list>
                <text> row1col1 </text>
                <text> row1col2 </text>
            </list>
            <list>
                <text> row2col1 </text>
                <text> row2col2 </text>
            </list>
        </table>
    </slide>
</slideshow>
