<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE slideshow[
        <!ELEMENT slideshow (title, author, date, slide+)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT date (#PCDATA)>

        <!ELEMENT slide (text|image|list|table)*>
        <!ATTLIST slide background CDATA #IMPLIED>

        <!ELEMENT text (#PCDATA)>
        <!ATTLIST text color CDATA #IMPLIED>
        <!ATTLIST text font CDATA #IMPLIED>
        <!ATTLIST text size CDATA #IMPLIED>

        <!ELEMENT image EMPTY>
        <!ATTLIST image src CDATA #REQUIRED>
        <!ATTLIST image width CDATA #REQUIRED>
        <!ATTLIST image height CDATA #REQUIRED>

        <!ELEMENT list (text|image|list|table)*>
        <!ATTLIST list bullet_point CDATA #IMPLIED>

        <!ELEMENT table (row)*>
        <!ELEMENT row (text|image|list|table)*>
        <!ATTLIST table rows CDATA #REQUIRED>
        <!ATTLIST table cols CDATA #REQUIRED>
        ]>
<slideshow>
    <title>My first slide show</title>
    <author>John Doe</author>
    <date>02-10-2022</date>
    <slide>
        <text> test1 </text>
        <text> test2 </text>
        <text> test3 </text>
    </slide>
    <slide>
        <text>this is a list</text>
        <list>
            <text> hello world </text>
            <image src="examples/cat.png" width="100" height="100"/>
            <list>
                <text> list_item1 </text>
                <text> list_item2 </text>
            </list>
            <text> na de sublist </text>
        </list>
    </slide>
    <slide>
        <text>This is a table</text>
        <table rows="3" cols="2">
            <row>
                <text> row1col1 </text>
                <text> row1col2 </text>
            </row>
            <row>
                <text> row2col1 </text>
                <text> row2col2 </text>
            </row>
            <row>
                <text> 1 </text>
                <text> b </text>
            </row>
        </table>
        <text>na de tabel</text>
    </slide>
</slideshow>